// <auto-generated />
using System;
using GAE.Engine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GAE.Engine.Data.Migrations
{
    [DbContext(typeof(GaeDbContext))]
    [Migration("20260406061311_AddMultiWorldPhase1Foundation")]
    partial class AddMultiWorldPhase1Foundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GAE.Engine.Data.CombatStateEntity", b =>
                {
                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<string>("WorldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("default-world")
                        .HasColumnName("world_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RoomId", "WorldId");

                    b.ToTable("combat_states", (string)null);
                });

            modelBuilder.Entity("GAE.Engine.Data.ContentRegistryEntity", b =>
                {
                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ContentType", "Id");

                    b.HasIndex("ContentType")
                        .HasDatabaseName("ix_content_registry_type");

                    b.HasIndex("ContentType", "Name")
                        .HasDatabaseName("ix_content_registry_type_name");

                    b.ToTable("content_registry", (string)null);
                });

            modelBuilder.Entity("GAE.Engine.Data.ConversationLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("latency_ms");

                    b.Property<string>("LogId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("log_id");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation");

                    b.Property<string>("PlayerId")
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response");

                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_prompt");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_conversation_logs_player_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_conversation_logs_timestamp");

                    b.ToTable("conversation_logs", (string)null);
                });

            modelBuilder.Entity("GAE.Engine.Data.GameConfigEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("game_config", (string)null);
                });

            modelBuilder.Entity("GAE.Engine.Data.GameEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("Narration")
                        .HasColumnType("text")
                        .HasColumnName("narration");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.Property<string>("RoomId")
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_game_events_created_at");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_game_events_player_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_game_events_type");

                    b.ToTable("game_events", (string)null);
                });

            modelBuilder.Entity("GAE.Engine.Data.PartyQuestEntity", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("text")
                        .HasColumnName("group_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("GroupId");

                    b.ToTable("party_quests", (string)null);
                });

            modelBuilder.Entity("GAE.Engine.Data.PlayerEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ActiveWorldId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("default-world")
                        .HasColumnName("active_world_id");

                    b.Property<string>("Backstory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("backstory");

                    b.Property<int>("Cha")
                        .HasColumnType("integer")
                        .HasColumnName("cha");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("class");

                    b.Property<int>("Con")
                        .HasColumnType("integer")
                        .HasColumnName("con");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentRoomId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_room_id");

                    b.Property<int>("Dex")
                        .HasColumnType("integer")
                        .HasColumnName("dex");

                    b.Property<string>("DiscordId")
                        .HasColumnType("text")
                        .HasColumnName("discord_id");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("equipment");

                    b.Property<string>("Faction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("faction");

                    b.Property<int>("Gold")
                        .HasColumnType("integer")
                        .HasColumnName("gold");

                    b.Property<bool>("HasCompletedDemo")
                        .HasColumnType("boolean")
                        .HasColumnName("has_completed_demo");

                    b.Property<string>("HomeWorldId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("default-world")
                        .HasColumnName("home_world_id");

                    b.Property<int>("Hp")
                        .HasColumnType("integer")
                        .HasColumnName("hp");

                    b.Property<int>("Int")
                        .HasColumnType("integer")
                        .HasColumnName("int");

                    b.Property<string>("Interaction")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("interaction");

                    b.Property<string>("Inventory")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("inventory");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("Luck")
                        .HasColumnType("integer")
                        .HasColumnName("luck");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer")
                        .HasColumnName("max_hp");

                    b.Property<int>("MaxMp")
                        .HasColumnType("integer")
                        .HasColumnName("max_mp");

                    b.Property<int>("Mp")
                        .HasColumnType("integer")
                        .HasColumnName("mp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("QuestLog")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("quest_log");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("race");

                    b.Property<string>("Spellbook")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("spellbook");

                    b.Property<string>("StatusEffects")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("status_effects");

                    b.Property<int>("Str")
                        .HasColumnType("integer")
                        .HasColumnName("str");

                    b.Property<long?>("ThreadId")
                        .HasColumnType("bigint")
                        .HasColumnName("thread_id");

                    b.Property<int>("Wis")
                        .HasColumnType("integer")
                        .HasColumnName("wis");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasColumnName("xp");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRoomId")
                        .HasDatabaseName("ix_players_current_room_id");

                    b.HasIndex("DiscordId")
                        .IsUnique()
                        .HasDatabaseName("ix_players_discord_id")
                        .HasFilter("discord_id IS NOT NULL");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("GAE.Engine.Data.PlayerRoomEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AsciiArt")
                        .HasColumnType("text")
                        .HasColumnName("ascii_art");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<string>("EnvironmentTags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("environment_tags");

                    b.Property<string>("Exits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("exits");

                    b.Property<bool>("IsDiscovered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_discovered");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Npcs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("npcs");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<string>("WorldId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("default-world")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_player_rooms_player_id");

                    b.HasIndex("PlayerId", "RoomId", "WorldId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_rooms_player_room");

                    b.ToTable("player_rooms", (string)null);
                });

            modelBuilder.Entity("GAE.Engine.Data.PlayerWorldStateEntity", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.Property<string>("WorldId")
                        .HasColumnType("text")
                        .HasColumnName("world_id");

                    b.Property<string>("CurrentRoomId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_room_id");

                    b.Property<DateTimeOffset?>("FirstVisitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_visited_at");

                    b.Property<bool>("HasVisited")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_visited");

                    b.Property<DateTimeOffset?>("LastVisitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visited_at");

                    b.HasKey("PlayerId", "WorldId");

                    b.ToTable("player_world_states", (string)null);
                });

            modelBuilder.Entity("GAE.Engine.Data.RoomEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AsciiArt")
                        .HasColumnType("text")
                        .HasColumnName("ascii_art");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<string>("EnvironmentTags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("environment_tags");

                    b.Property<string>("Exits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("exits");

                    b.Property<bool>("IsDiscovered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_discovered");

                    b.Property<bool>("IsTemplate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_template");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("items");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Npcs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("npcs");

                    b.Property<string>("WorldIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("world_ids")
                        .HasDefaultValueSql("'[\"default-world\"]'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("IsTemplate")
                        .HasDatabaseName("ix_rooms_is_template")
                        .HasFilter("is_template = true");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("GAE.Engine.Data.StatTranslationHistoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DestinationWorldId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_world_id");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.Property<string>("SourceWorldId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_world_id");

                    b.Property<string>("TranslatedStats")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("translated_stats");

                    b.Property<string>("TranslationNotes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("translation_notes");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "SourceWorldId", "DestinationWorldId");

                    b.ToTable("stat_translation_history", (string)null);
                });

            modelBuilder.Entity("GAE.Engine.Data.StoryEntryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ActionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_id");

                    b.Property<string>("MechanicalSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mechanical_summary");

                    b.Property<string>("Narration")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("narration");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.Property<string>("RawInput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_input");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("WorldId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("default-world")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_story_entries_player_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_story_entries_room_id");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_story_entries_timestamp");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_story_entries_world_id");

                    b.ToTable("story_entries", (string)null);
                });

            modelBuilder.Entity("GAE.Engine.Data.WorldEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Portals")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("portals");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rules");

                    b.Property<string>("SpawnRoomId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spawn_room_id");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("GAE.Engine.Data.WorldNpcStateEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DispositionState")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("disposition_state");

                    b.Property<string>("KnowledgeScopeOverrides")
                        .HasColumnType("jsonb")
                        .HasColumnName("knowledge_scope_overrides");

                    b.Property<string>("NpcId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("npc_id");

                    b.Property<string>("PlayerId")
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.Property<string>("WorldId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("NpcId", "WorldId", "PlayerId")
                        .IsUnique();

                    b.ToTable("world_npc_states", (string)null);
                });

            modelBuilder.Entity("GAE.Engine.Data.WorldStatSnapshotEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Class")
                        .HasColumnType("text")
                        .HasColumnName("class");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Hp")
                        .HasColumnType("integer")
                        .HasColumnName("hp");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("MaxHp")
                        .HasColumnType("integer")
                        .HasColumnName("max_hp");

                    b.Property<int>("MaxMp")
                        .HasColumnType("integer")
                        .HasColumnName("max_mp");

                    b.Property<int>("Mp")
                        .HasColumnType("integer")
                        .HasColumnName("mp");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.Property<string>("Race")
                        .HasColumnType("text")
                        .HasColumnName("race");

                    b.Property<string>("Stats")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stats");

                    b.Property<string>("WorldId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("world_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "WorldId")
                        .IsUnique();

                    b.ToTable("world_stat_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
